### PR TITLE
Add flake8 to find syntax errors & undefined names

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by kriadmin** [comment]
This will not work as all the code is in `.md` files. If you can implement this as a script to lint the files then it will be much appreciated.

**P.S.** I am already using autopep8. Isn't that enough?

**Comment by cclauss** [comment]
autopep8 is only about "style violations" which is the second pass of flake8 which runs in --exit-zero mode anyway.  I find that the five tests (--select=E901,E999,F821,F822,F823) in the first pass are far more interesting/important because they find issues that can halt your program at runtime.

I added __--exclude=website__ so that flake8 ignores third party code (Flask, Jinga, etc.)

**Comment by kriadmin** [comment]
Can you implement it as an module? You can use the `util` script to read the snippets and thier code and then you lint it if flake8 exists as an module?

**Comment by cclauss** [comment]
flake8 can be run as a module: __python -m flake8__

**Comment by kriadmin** [comment]
You are not understanding what I mean. I want to run it on all the markdown files in the snippets folder.

**Comment by cclauss** [comment]
flake8 runs on files that have a .py suffix, not those with a .md suffix.  If you can provide the code that converts .md files into .py files then we can run that code as part of the travis job, run flake8 against them and then delete those temporary .py files.

**Comment by kriadmin** [comment]
Ok i will try to do it

**Comment by cclauss** [comment]
Do you know why __python3 website/main.py__ is failing?

**Comment by kriadmin** [comment]
@cclauss Yeah it is due to some issues in the tag_database but I would recommend to use the gitter chat for questions like these.

**Comment by kriadmin** [comment]
@cclauss Ok I sorted it out! Add the following code in a new file in script directory :- 
```py
import util
import flake8
import subprocess
import sys
for snippet in util.read_snippets():
    code = snippet.read_code()
    check_1 = subprocess.run(['flake8', '-','--select=E901,E999,F821,F822,F823','--count','--show-source','--statistics'], input=code, encoding='utf8',stdout=subprocess.PIPE)
    check_2 = subprocess.run(['flake8', '-','--exit-zero','--max-complexity=10','--count','--max-line-length=127','--statistics','--ignore=W292'], input=code, encoding='utf8',stdout=subprocess.PIPE)
    check_1.check_returncode()
    check_2.check_returncode()
``` 
**P.S.** I just want you to get the credit. If you want me to do it tell me :smile:

**Comment by cclauss** [comment]
I bet you can comment out __import flake8__.  Go ahead and put it in place.  I am on a long drive w/o laptop.

**Comment by kriadmin** [comment]
Oh yeah ok :+1:

**Pull request closed without merging**
