### PR TITLE
[feature]added sorting algorithm

### PR DESCRIPTION
**Pull request by sachans**
Added a sorting algorithm.

## Description

**Resolves** #(issue number) 

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. 
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by sachans** [comment]
@kriadmin Can you help me find why travis ci is not able to build readme.md.

**Comment by kriadmin** [comment]
@sachans Due to (board) exams I am busy for this month. I will review it and merge it when I come back.

**Comment by kriadmin** [comment]
Thanks for contributing :+1:

**Comment by sachans** [comment]
But it is not showing that you merged

**Comment by kriadmin** [comment]
Oops sorry. I merged it now

**Pull request merged**
